### ISSUE TITLE
create album is no longer supported

### ISSUE THREAD

**Issue by grandvizier** [esteban-uo/picasa#25]
what was added here https://github.com/esteban-uo/picasa/commit/924c8e9bb0e438136105a4df14bb4b7c34f808a3 is no longer supported in version 3.0 of the API
https://developers.google.com/picasa-web/docs/3.0/releasenotes

```
 Error: UNKNOWN_ERROR
    at Request.request.(anonymous function).error [as _callback] (/myApp/node_modules/picasa/src/executeRequest.js:11:28)
    at Request.self.callback (/myApp/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/myApp/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/myApp/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20) statusCode: 400, body: 'Insert is no longer supported
```
maybe this can be bypassed with specifying version 2:
https://developers.google.com/picasa-web/docs/2.0/developers_guide_protocol#Versioning
but more likely this feature should be removed

**Comment by esteban-uo** [comment]
Great! thanks for the information @grandvizier . I'll update it soon... many things from Google API are not really working... and its future is sadly not clear yet
