### ISSUE TITLE
Example not working due to syntax error

### ISSUE THREAD

**Issue by yauh** [esteban-uo/picasa#9]
I am having trouble running the example from the repo due to a syntax error:

```
MacBook:examples stephan$ node getAccessToken.js
/Users/stephan/Downloads/picasa-master/examples/config.js:7
  clientSecret : 'secrettoken'
  ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/stephan/Downloads/picasa-master/examples/getAccessToken.js:4:16)
    at Module._compile (module.js:570:32)
MacBook:examples stephan$ node -v
v6.9.1
MacBook:examples stephan$ npm -v
4.0.2
```

**Comment by esteban-uo** [comment]
hi @yauh can you paste your config.js example to help you out more?

**Comment by yauh** [comment]
```// Get config here API Manager > Credentials
// https://console.developers.google.com/home/dashboard

const config = {
  clientId     : '1234-n20eeivkorul7b50im9fk3qub8tce7vg.apps.googleusercontent.com',
  redirectURI  : 'http://localhost'
  clientSecret : '*******'
}

module.exports = config
```

**Comment by yauh** [comment]
Oh shit. I am too stupid to add a comma after `redirectURI`. Consider it solved.

**Comment by esteban-uo** [comment]
Awesome! at least was something simple!, let me know if you are in troubles. I'll try to create a project example soon just in case.
